#!/usr/bin/env bash
#
# symlink the font file to figlet's font directory.
#

figlet_fonts_dir=$(figlet -I2)          # /usr/share/figlet/fonts

figlet_tag=$(basename "$(cd "$(dirname "$0")" && pwd )")
cd "$(dirname "$0")/.."

sudo stow -S $figlet_tag -t $figlet_fonts_dir --ignore=install -v

unset figlet_fonts_dir figlet_tag
